### PR TITLE
use expiring_url for attachment links

### PR DESCRIPTION
**Pull request by soberstadt**

### CODE REVIEW

**Comment by twinge** [comment]
:+1:

**Comment by andrewroth** [comment]
I'll make sure to try this on cap staging site first before updating production.  I think it should be fine though.

**Comment by soberstadt** [comment]
How are you configuring this that it works on cap currently?

**Comment by andrewroth** [comment]
I know I just chatted this on hipchat but just for the log on this issue:

https://github.com/CruGlobal/cap/blob/master/app/decorators/models/fe/answer_decorator.rb#L2
https://github.com/CruGlobal/cap/blob/master/app/controllers/applications_controller.rb#L26
https://github.com/CruGlobal/cap/blob/master/config/initializers/paperclip.rb#L2

is the relevant code on cap

**Comment by andrewroth** [comment]
Btw, I would be happy to move some of that code into FE or otherwise use FE methods over the custom cap stuff there

**Comment by soberstadt** [comment]
@andrewroth can you double check this today please?

**Comment by andrewroth** [comment]
Yeah, I just checked it.. it still works in cap so we're good to merge

**Comment by andrewroth** [comment]
@soberstadt @twinge when you use an expiring_url, it does have the AWSAccessKeyId and Signature right in the url.. is that a danger?  It's starting to come back to me now, that I think I went with a get method that redirects to an expiring url.  A competent person could still get the access key and signature but it would be more difficult.

**Comment by andrewroth** [comment]
@soberstadt I added a bit of code to set the @saved_at_timestamp when you save an attachment

**Comment by andrewroth** [comment]
I've removed the cap override for update.js.erb, I think we can use the (new) FE one.  One less file to maintain.

**Comment by twinge** [comment]
That's not a concern.

**Comment by andrewroth** [comment]
Ok, so once this is committed, when I merge it to cap, I'll make everything use expiring_urls directly then without going through ApplicationsController#download_attachment_field.  :+1: once the DateTime check is cleaned

**Comment by twinge** [comment]
Just to elaborate a bit, the concern isn't that someone will see your access key. The concern is share-ability of the expiring links. I think the idea of #download_attachment_field was to make it so i couldn't copy/paste the link and send it to someone and have it work for them without them logging in. #expiring_url allows you to pass in an amount of time that it's valid for. Default is 1 hour. The shorter you make it, the more secure it is, but the more likely the user will get an access denied error (if they had the page open too long before clicking the download link).

In the context of where it's used in Panorama, that's not really a concern. Depending on the contents of the file being downloaded, it's possible some other system might not be okay with that.

**Comment by andrewroth** [comment]
@twinge I see.. thanks for the context.. I guess when I saw AWSAccessKeyId and Signature I assumed it was the keys to the s3 account, and assumed that anyone could stick those into any s3 client and be able to list and access all the files.  Is that not the case then?

**Comment by soberstadt** [comment]
Relevant doc: http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationQueryStringAuth

**Comment by twinge** [comment]
It's the key, but not your secret. your secret is used to sign the
signature, but is not actually embedded in it.

**Pull request merged**
