### PR TITLE
Make fe work with turbo-rails

### PR DESCRIPTION
**Pull request by jbirdjavi**
There are a few things here that I needed to do to get it to work on Global360 with turbo-rails and importmaps:
- load javascript after turbo:load events
- make sure all variables are declared (I used let everywhere)
- add the spinner.gif file

I don't believe that any of this would break existing apps, but may be worth testing?

### CODE REVIEW

**Comment by jbirdjavi** [comment]
@andrewroth Can you review this please? :)

**Comment by andrewroth** [comment]
Just curious, what app is this for?

Looks fine to me.

But for every app we update fe to this, it would be wise to run through an application submit and references submit to make sure it all works.

**Comment by jbirdjavi** [comment]
I've got this working with Global360 currently. I'll be using this with Summer Missions on the Rails 7 upgrade there too.

**Comment by andrewroth** [comment]
rails turbolinks has always given me issues and been way more work than it was worth. First thing I do on a new rails app is remove turbolinks. Though this was years ago, maybe it's better now, or maybe I wasn't doing it right.

**Comment by jbirdjavi** [comment]
I've also had issues with turbolinks in the past. But I think with the transition to turbo in Rails 7, there's some really good stuff in it and I'd like to get it to work with our apps. I also have a better understanding of the issues now (like needing our JS code to fire after `turbo:load` events).

**Pull request merged**
