### PR TITLE
Fe share

### PR DESCRIPTION
**Pull request by andrewroth**
@twinge This PR restricts the "add existing" dialog to only items that are explicitly checked off as to be shared.  it also changes the wording to be "copying" elements instead of re-using them.  I've found people are always confused when using the same actual element, and copying it a much better approach.  If there are no elements to copy, it goes on directly to create a new element

### CODE REVIEW

**Comment by andrewroth** [comment]
Just realized that we probably want to set share to false after cloning, otherwise it would get confusing

**Comment by twinge** [comment]
Copying implies that we made a copy of something, as opposed to just linking the existing element to a new page.

**Comment by andrewroth** [comment]
That's exactly what we want to do (in Canada at least).. they find linking to existing elements confusing and it means you can't customize the element.

https://github.com/CruGlobal/qe/pull/34/files#diff-74c5018a5db777424c2a188163320719R33 is the change to a copy instead of linking

**Comment by twinge** [comment]
The reason we link instead of copy is that it's important that the answers
are tied to the same question. That allows students to switch to applying
for a different project that uses a different form and not lose all their
answers. If the elements were copied, the data wouldn't be linked, and
they'd have to start over in that situation.

Maybe we need to offer both options?

**Comment by andrewroth** [comment]
I guess we could have both a Copy and Insert, and make use of the Fe.never_reuse_elements to hide Copy if it's set?  Or we could use Insert for you guys and only show copy for Fe.never_reuse_elements and save having to explain to the user what the difference is on the dialog?

**Comment by twinge** [comment]
If never_reuse_elements is set, then it should always be a copy.

**Comment by andrewroth** [comment]
Forgot about this. I meant..

Fe.never_reuse_elements set: only use Copy
Fe.never_reuse_elements NOT set: use both Copy and Use Existing?  Or just Use Existing?

**Comment by twinge** [comment]
I'm fine with this:

Fe.never_reuse_elements set: only use Copy
Fe.never_reuse_elements NOT set: use both Copy and Use Existing

**Comment by andrewroth** [comment]
@twinge merge the latest fe work and did another attempt at this with the logic you're good with.

Two options for displaying the actual list.  1) one row per item, "<Insert> <Copy> label" .. looks nicer initially but the disable-with makes it awkward (https://www.dropbox.com/s/b8t7n0eg9wsil2m/Screen%20shot%202015-10-05%20at%207.54.30%20PM.png?dl=0)  or 2) two rows per item, looks worse initially but the disable-with looks right. (https://www.dropbox.com/s/96fpezn049msdl4/Screen%20shot%202015-10-05%20at%207.56.14%20PM.png?dl=0)

Since it's just admins basically that will be using this, I went with 2) but I can go with 1) and try to fix it up if you prefer.

**Comment by twinge** [comment]
I prefer option 1, and disable both buttons when either of them is clicked.

**Comment by andrewroth** [comment]
Sorry this went to the back-burner as I focused on other cap tasks.. how's this?

https://www.dropbox.com/s/4wk540vi94inp90/Screen%20shot%202015-10-14%20at%2012.12.12%20PM.png?dl=0
https://www.dropbox.com/s/kvjrds4vnuveg8s/Screen%20shot%202015-10-14%20at%2012.12.28%20PM.png?dl=0

**Comment by twinge** [comment]
:+1:

**Pull request closed without merging**
