### PR TITLE
Update methods stored on $ obj

### PR DESCRIPTION
**Pull request by mgeatz**
Move custom methods current stored on the $ obj to the window obj, to avoid TSYS jQuery download overwrite.

### CODE REVIEW

**Comment by andrewroth** [comment]
Just important to note that a few of the apps I've worked on at least either define some custom stuff on $.fe or invoke $.fe methods in certain places.  This looks like a necessary change for sure to handle TSYS, but it will take some knowledge of this change when updating FE on other apps to not break things.  Maybe those apps can just manually do $.fe = window.fe since they won't care about avoiding that conflict?

**Comment by mgeatz** [comment]
Good point @andrewroth. Yeah, for those apps we'll need to find/replace $.fe with window.fe or just assign $.fe to window.fe as you've suggested. I suppose we could publish a new version of 'fe' and use the new version in TSYS related applications, and old version where $.fe is being used. With you suggestion, updating each app should be a relatively trivial task. Do you have a list of the apps using the fe gem?

**Comment by andrewroth** [comment]
The ones I've worked on are one-app/cap and mydevelopment/pr.  I think SMT too, but that one might be using an older revision of FE.

Maybe we could define a function that sets window.fe, and call that only in the TSYS case?  Since there is only one app that needs to handle the conflict, but several apps that don't, it's actually less work for us.  Maybe @twinge wants $ to be overwritable for all apps though?

**Comment by twinge** [comment]
@mgeatz is already working on making SMT work with these changes. I can have him take a look at the other two as well.

**Comment by mgeatz** [comment]
@twinge if this looks good would you approve? I will update the one-app/cap and mydevelopment/pr repos to align with the new fe custom method storage solution.

**Pull request merged**
