### PR TITLE
Add attachment deletion feature

### PR DESCRIPTION
**Pull request by jbirdjavi**

### CODE REVIEW

**Comment by andrewroth** [comment]
Looks good.. is it possible to add a test?

**Comment by jbirdjavi** [comment]
Yes, it is possible. :)

**Comment by andrewroth** [comment]
All right, paging @twinge for the testing smack down ;)

**Comment by twinge** [comment]
@jbirdjavi Please add a test :)

**Comment by jbirdjavi** [comment]
I already added a test.

**Comment by andrewroth** [comment]
Sorry @jbirdjavi !  My mistake.  I didn't see it.

**Pull request merged**
