### PR TITLE
Show hidden page

### PR DESCRIPTION
**Pull request by jbirdjavi**
This needs #70 to be merged before it can be merged.

### CODE REVIEW

**Comment by andrewroth** [comment]
This is for viewing a page (as an evaluator might)?

**Comment by jbirdjavi** [comment]
Within the SMT, all the question sheets have hidden "Done" pages, which have actually never been used to this point.  But it would be helpful to be able to show that page when the application has been submitted, so this would allow us to do that and have different "Done" pages for different application types.

**Comment by andrewroth** [comment]
Ah, thanks for the context.  I guess what's confusing me is that you made a show method on answer pages, and the show method is usually used for viewing, and the edit method used for actually inputting data into the form.  Is this change intended to be seen by applicants or only evaluators?

**Comment by jbirdjavi** [comment]
It's intended to be seen by applicants (after they submit successfully).

**Comment by andrewroth** [comment]
Oh, interesting.. I see.. so you guys must be using your own view after submitted?  With CAP/OneApp I'm pretty sure we just stick to edit and the elements are frozen as per it being in submitted status.

**Comment by jbirdjavi** [comment]
Yeah, previously it redirected to a done page that was the same for every application.  Now that other organizations are using it, a universal done page doesn't work so well.

**Comment by andrewroth** [comment]
I think it would be possible for SPT to do a done page that uses the same FE code as the edit view.  It would function as a done page because all the elements would be frozen.  That said, I don't think it's a big deal if it's just easier for whatever reasons to use your own submitted view.  I think really your PR is two separate tasks: 1, add ability to force hidden pages to display, 2, add a way to view a specific page

**Comment by jbirdjavi** [comment]
Yeah, I initially was trying to use the edit method, but ran into some issues, mostly that there are checks in several places to see if the page is hidden, and I the ones in the view were particularly messy to do a check on.  So I just added the show method (since it's showing a single page without links to any of the other pages anyway) and gave it its own view.

**Comment by andrewroth** [comment]
Sounds good.  :+1: from me

**Pull request merged**
