### PR TITLE
handle jQuery 3 document ready change

### PR DESCRIPTION
**Pull request by andrewroth**

### CODE REVIEW

**Review by jbirdjavi — APPROVED** [review]
Is this the only file which has this sort of implementation?

**Comment by andrewroth** [comment]
Oh, the admin section uses it too. I guess it could go in fe.common and get included in both.

**Comment by jbirdjavi** [comment]
Yeah that might be good

**Comment by andrewroth** [comment]
Took the chance to also change the tabs to two spaces.

**Review by jbirdjavi — APPROVED** [review]

**Comment by dbenton9** [comment]
@andrewroth is this good to go? and if so can you deploy and update the gem?

**Comment by andrewroth** [comment]
> @andrewroth is this good to go? and if so can you deploy and update the gem?

Done!

**Pull request merged**
