### PR TITLE
add a helper to pull the css classes into an array

### PR DESCRIPTION
**Pull request by andrewroth**
@twinge

### CODE REVIEW

**Comment by twinge** [comment]
:+1: but curious what you're using this for.

**Comment by andrewroth** [comment]
They want to show or hide the ministry interests page on CAP depending on which ministry you initially pick.  Some ministries care about the prefs, others don't.  To do that, I put an element on the welcome page, and added a class to hide it (using css).  But the app/views/fe/questions/fe/_ministry_picker.html.erb partial in CAP now needs to show ALL ministries for that specific element, but not for the other visible ministry pickers the user uses (which actually only show the sub-ministries available).  So I added the "all" class to the first hidden ministry picker to distinguish them, and use this to check for it.  Here: https://github.com/CruGlobal/cap/commit/94642e6dd620f3790f72c25f78934d9e435b0734#diff-f92f90e4581bb397b3d9f24a104a26adR8

I guess it's a bit of a shortcut and not really what css was intended for?  But it's so convenient compared to making a new element type or something like that.

**Comment by andrewroth** [comment]
Sorry I didn't really explain, the element on the welcome page is a ministry picker that uses the conditional page functionality to show or hide the Ministry Interests page depending on the ministry they choose.  You probably deduced that though..

**Comment by twinge** [comment]
got it

**Pull request merged**
